import './globals.css'
import type { Metadata } from 'next'
import { Roboto_Flex as Roboto, Poppins } from 'next/font/google'
import { ReactNode } from 'react'

const roboto = Roboto({ subsets: ['latin'], variable: '--font-roboto' })
const poppins = Poppins({ subsets: ['latin'], weight: ['700', '800'], variable: '--font-poppins' })

export const metadata: Metadata = {
  title: 'EcoHomeAI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={`${roboto.variable} ${poppins.variable} font-sans`}>{children}</body>
    </html>
  )
}
